new_cols:
  score:
    kills: 3
    assists: 2
    total cs: 0.02
    firstbloodkill: 2
    triplekills: 2
    quadrakills: 2
    pentakills: 3
    deaths: -1

filtered_data:
  leagues:
    - LCK
    - LCS
    - LEC
    - NA LCS
    - EU LCS